config/routes.rb
Olark::Application.routes.draw do

  resources :chats
  root :to => "chats#index"
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  attr_accessible :browser, :city, :country, :country_code, :email_address, :fullname, :olark_id, :visitor_id, :ip, :kind, :operating_system, :organization, :region, :data

  def self.new_from_json(params)
    params = JSON.parse(params[:data])
    Rails.logger.info params.class
    new({
          kind:             params[:kind],
          olark_id:         params[:olark_id],
          visitor_id:       params[:visitor][:visitor_id],
          fullname:         params[:visitor]['fullName'],
          email_address:    params[:visitor]['emailAddress'],
          city:             params[:visitor][:city],
          region:           params[:visitor][:region],
          country:          params[:visitor][:country],
          country_code:     params[:visitor]['countryCode'],
          organization:     params[:visitor][:organization],
          ip:               params[:visitor][:ip],
          browser:          params[:visitor][:browser],
          operating_system: params[:visitor]['operatingSystem'],
        })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def create
    @chat = Chat.new_from_json(params)

    respond_to do |format|
      if @chat.save
        flash[:notice] = 'Chat was successfully created.'
        format.json { render json: @chat, status: :created }
      else
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def index
    @chats = Chat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chats }
    end
  end
  
  def show
    @chat = Chat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chat }
    end
  end
  
  def update
    @chat = Chat.find(params[:id])

    respond_to do |format|
      if @chat.update_attributes(params[:chat])
        format.html { redirect_to @chat, notice: 'chat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat = Chat.find(params[:id])
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url }
      format.json { head :no_content }
    end
  end
  
  def edit
    @chat = Chat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/chats/_form.html.erb
<%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %><br />
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :visitor_id %><br />
    <%= f.text_field :visitor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<center><h4>Chats</h4></center></br>
<table>
  <tr>
    <th>Visitor ID</th>
    <th>Full Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chats.each do |chat| %>
  <% unless chat.id.blank? %>
  <tr>
    <td><%= link_to chat.visitor_id, chat %></td>
    <td><%= link_to chat.fullname, chat %></td>
  </tr>
  <% end %>
<% end %>
</table>

app/views/chats/new.html.erb
<h1>New chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Olark</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>